CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    item_id BIGINT,
    address_detail TEXT
);

CREATE TABLE line_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    item_id BIGINT,
    quantity INTEGER NOT NULL,
    price NUMERIC(19, 2),
    CONSTRAINT fk_line_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders (id)
);
